"""version final 

Revision ID: bfaf29d53bbe
Revises: bd4caefe78a2
Create Date: 2026-02-05 12:01:13.714425

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfaf29d53bbe'
down_revision: Union[str, Sequence[str], None] = 'bd4caefe78a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('current_agent', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('total_interactions', sa.INTEGER(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_contexts_session_id'), 'agent_contexts', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_contexts_user_id'), 'agent_contexts', ['user_id'], unique=False)
    op.create_table('utilisateur',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motDePasseHash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', postgresql.ENUM('ETUDIANT', 'PROFESSEUR', 'Administrateur', name='statututilisateur'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('etudiant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domaine', postgresql.ENUM('INFORMATIQUE', 'DATA_SCIENCE', 'DROIT', 'MARKETING', 'CHIMIE', 'PHYSIQUE', 'MEDECINE', 'BIOLOGIE', 'ECONOMIE', 'MANAGEMENT', 'GENERAL', name='domaine'), nullable=False),
    sa.Column('niveau_technique', sa.Integer(), nullable=False),
    sa.Column('competences', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('objectifs_apprentissage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motivation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('niveau_energie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professeur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domaine', postgresql.ENUM('INFORMATIQUE', 'DATA_SCIENCE', 'DROIT', 'MARKETING', 'CHIMIE', 'PHYSIQUE', 'MEDECINE', 'BIOLOGIE', 'ECONOMIE', 'MANAGEMENT', 'GENERAL', name='domaine'), nullable=False),
    sa.Column('niveau_experience', sa.Integer(), nullable=False),
    sa.Column('specialites', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('motivation_principale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('niveau_technologique', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professeur')
    op.drop_table('etudiant')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_agent_contexts_user_id'), table_name='agent_contexts')
    op.drop_index(op.f('ix_agent_contexts_session_id'), table_name='agent_contexts')
    op.drop_table('agent_contexts')
    # ### end Alembic commands ###
